version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies (if any)..."
      # For Python, you might install requirements here if you had a requirements.txt file
      #- pip install -r requirements.txt
  build:
    commands:
      - echo "Building the application..."
      - echo "Running a simple test..."
      - python app.py # Execute the Python script
  post_build:
    commands:
      - echo "Build completed. Packaging artifacts..."
      - aws s3 cp app.py s3://$CODEBUILD_ARTIFACTS_BUCKET/ # Copy the script to the artifacts bucket
artifacts:
  files:
    - app.py
    




















